Comment:
  type: entity
  table: comments
  id:
    id:
      type: integer
      generator:
       strategy: AUTO
  fields:
    user_id:
      type: integer
    message:
      type: string
    created_at:
      type: datetime
